### ISSUE TITLE
Board is not detected

### ISSUE THREAD

**Issue by naus3a** [thisisnoiseinc/NMCode#1]
Following the instructions in the readme, I:
* installed `ESP32` support on the `Arduino` IDE
* selected the `ESP32 Pico` as the selected board

~but, when I connected the NM via USB no hardware was detected and no port was found in the `Arduino` IDE.~
~I imagined it could be a missing USB<->UART driver, so I installed the Silab drivers ( https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers ), but nothing changed.~
~I tried both on Osx and Windows, but always had the same result.~

~Is there something crucial I'm missing? Is there anything specific I should do, in order to be able to upload software to the controller?~

Edit: I unscrewed the top and saw that the USB port is only connected to battery; so let me reword my original question: can you give me a few hints on how to hookup the board to a USB port for flashing?

**Comment by thisisnoiseinc** [comment]
Hey Enrico,

The ESP32 chip unfortunately does not have native USB capabilities, which means you will have to code it via the pins located behind the knob.

Further, you will need a TTL Serial adapter to code the device. We’ve attached one that we’ve used with success below:

https://www.amazon.ca/gp/product/B01JG8H5U4/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 <https://www.amazon.ca/gp/product/B01JG8H5U4/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1>

Also, here is a snapshot of the pins for reference:



If you have any specific questions just let us know, happy to help :)

Cheers,

- Zach

**Comment by thisisnoiseinc** [comment]
Also, you may need to change the board to “FireBeetle-ESP32” if you have a
newer unit.

Cheers,

- Zach

**Comment by naus3a** [comment]
Thanks a lot for the quick feedback: getting myself an adapter board!
It looks like the pin picture did not make it into the message: if you can try to re-upload thanks, otherwise I will try to figure it out :)

**Comment by thisisnoiseinc** [comment]
Apologies!

Here the file is in a .zip format instead:



Best of luck,

- Zach

**Comment by callmewilko** [comment]
Hi @thisisnoiseinc  would it be possible to add the pin diagram, perhaps in the repo in a 'programming' folder or similar please? I also want to have a go at hacking my code into the unit. It would be much appreciated :-) If I get it working I'll fork it and open a PR adding some more detail in a README.

**Comment by thisisnoiseinc** [comment]
Done!

NMCode/README.md at main · thisisnoiseinc/NMCode (github.com)
<https://github.com/thisisnoiseinc/NMCode/blob/main/README.md>

Be sure to let us know what you create :)

- Zach

**Comment by callmewilko** [comment]
@thisisnoiseinc thanks!
